# Generated by Django 3.0.5 on 2020-05-19 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_Assembly', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(max_length=256)),
                ('Drawing', models.FileField(upload_to='')),
                ('Model_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.Model_Name')),
                ('Sub_Assembly_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.Sub_Assembly')),
            ],
        ),
    ]
