# Generated by Django 3.0.5 on 2020-05-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_Details',
            new_name='Item_Detail',
        ),
    ]
