# Generated by Django 3.0.5 on 2020-05-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_auto_20200519_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_assembly',
            old_name='sub_Assembly',
            new_name='sub_assembly',
        ),
    ]
