# Generated by Django 3.0.5 on 2020-05-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0003_auto_20200519_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='item_detail',
            name='Blank_drawing',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item_detail',
            name='Details',
            field=models.ImageField(blank=True, help_text='optional', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item_detail',
            name='Photo',
            field=models.ImageField(blank=True, help_text='optional', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item_detail',
            name='Process_Instructions',
            field=models.TextField(blank=True, help_text='optional', null=True),
        ),
        migrations.AlterField(
            model_name='item_detail',
            name='Drawing',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item_detail',
            name='Model_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bom.Model_Name'),
        ),
        migrations.AlterField(
            model_name='item_detail',
            name='Size',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='item_detail',
            name='Sub_Assembly_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bom.Sub_Assembly'),
        ),
        migrations.AddField(
            model_name='item_detail',
            name='Raw_Material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bom.Material'),
        ),
    ]
