# Generated by Django 3.0.5 on 2020-05-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0004_auto_20200519_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_detail',
            old_name='Blank_drawing',
            new_name='Drawing1',
        ),
        migrations.RenameField(
            model_name='item_detail',
            old_name='Drawing',
            new_name='Drawing2',
        ),
        migrations.RenameField(
            model_name='item_detail',
            old_name='Details',
            new_name='Photo1',
        ),
        migrations.RenameField(
            model_name='item_detail',
            old_name='Photo',
            new_name='Photo2',
        ),
    ]
